### ISSUE TITLE
bug: WithEventFilter in SetupWithManager is configured wrongly

### ISSUE THREAD

**Issue by portly-halicore-76** [belastingdienst/opr-paas#42]
# Bug Report

**PAAS Operator version:**

v0.8.5 / main

**Current behavior:**

In revision: 413cba22b1411e75f02e142ef196dfae58538bca an eventFilter was introduced to only reconcile when there are changes in the specblock of the managed Resources. However, a wrong type of predicates has been used to program this. Therefore the filter shouldn't work.

**Expected behavior:**

Filter the reconcile requests to only reconcile when spec updates are done. 

**Steps to reproduce:**

not relevant

**Related code:**

The wrong filters are used here: 

https://github.com/belastingdienst/opr-paas/blob/main/internal/controller/paas_controller.go#L177-L183
https://github.com/belastingdienst/opr-paas/blob/main/internal/controller/paasns_controller.go#L203-L209

**Other information:**

Here is described, how we should implement an eventFilter for filtering events if any. 

https://sdk.operatorframework.io/docs/building-operators/golang/references/event-filtering/#using-predicates

**Comment by devotional-phoenix-97** [comment]
Hmm, we probably need to understand the real issue first.

Just before we introduced these predicates, we had implemented updates to the Status field and ran into deadloops, where de Reconcile loop was triggered, updated the status field, which in turn triggered the reconcile loop, and round and round we went.

We therefore introduced these predicates, so that:
- a change to the spec field **would** trigger the reconcile loop (annotation too, btw)...
- a change to the label field **would** also trigger the reconcile loop
- a change to the status field **would not** trigger the reconcile loop

The implementation is also described [here](https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/predicate/predicate.go#L230), nearly identical as implemented.
And by looking for changes to GenerationChangedPredicate I also noticed [this](https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.0.0/#library-changes), which also seems in line with the implementation we introduced here.

You point to Event Filtering, which Iooked at earlier, and took as 'Custom Event Filtering', where the default predicates we implemented seem to do the job just fine.

I am fine with implementing a custom predicate, but wonder what it would fix.

Could you let us known how you got to the following conclusion?
> a wrong type of predicates has been used to program this. Therefore the filter shouldn't work.

**Comment by portly-halicore-76** [comment]
False positive of Intellij in this case. Works as a charme.
